.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH GPHPEDIT 1 "November 26, 2004"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
gPHPEdit \- a PHP/HTML/CSS Development Environment for GNOME
.SH SYNOPSIS
.B gphpedit
.RI [-?|--help]
.RI [--usage]
.RI [--display=DISPLAY]
.RI [--version]
.RI [files]
.br
.SH DESCRIPTION
gPHPEdit is a GNOME2 editor specialised for editing PHP scripts and related files (HTML/CSS/JS).
.PP
.SH OPTIONS
This program follows the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
For a complete description, see the Info files.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show version of program.
.TP
.B \-\-display=DISPLAY
Choose with with display to work with (if different from the value of $DISPLAY).
.br
.SH AUTHOR
gPHPEdit was written by Andy Jeffries <andy@gphpedit.org>

.PP
This manual page was written by Lior Kaplan <webmaster@guides.co.il>,
for the Debian project (but may be used by others).
